language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- echo $TRAVIS_TAG
- echo $(git describe --abbrev=0 --tags)
- bash scripts/deploy.sh $TRAVIS_BRANCH
script:
- npm test
- npm run build
deploy:
- provider: s3
  access_key_id: "$PROD_AWS_ACCESS_KEY_ID"
  secret_access_key: "$PROD_AWS_SECRET_ACCESS_KEY"
  bucket: "$PROD_AWS_BUCKET_NAME"
  local-dir: build
  skip_cleanup: true
  on:
    repo: ahdeshmukh/react-shopping-cart
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
env:
  global:
  - secure: upd9zt8PhH0A4DfJ4IFaWwT9UlnFC7/TQtDuXyyToOOfw/zIVh5c/g4mTL2mZPdVUjZfDHigY/IlhB03C+PFDVkx2FejFXNPAk+Ka8PJDwt/RgfOBCwY7S7aK6+dR82HRF7ePdhuqHEqYqM89PlPwwcZOY2ULUwVa/qplT+OQ2vJGaq+/iiDAhxCIlX7cATA2amSnTkoQEKMCu3qFZ0RkDESZS2EUxdMutRPOIXT7xpwgvl1+cZlp9rYhe8/Oe/qh9R/w9pi+aKFh3SeP4y4d1Z2YGs1uGeTChoGq1+I3xyvFpDD40C/a2fAANtDTmCHWoU8mJHvbT+/Caae7aaU2zIpewc5R3HgpZc7++VLB6FaFoVEOqkez4au+6NbiGj9CiZQiedq8svnFGd94TDHrcRp+2GJJg00VL6Yxv1hf3r3PC4yLS0Mc19T5uMs8g3jCtsHMXg00Z6KVPpFXZEJh5zaQG7M+pJ7kdarGBI5+8Ovr0TQdLTKByHI5IHtdGh2sHJilehUoh6AKNwKds9Na11auyDpPnqXrHihflnRXdK0TGAAuDV55VjCIMWMChEREdKlRXdWJysx3y3LFgxHZpnGR8HQESGz34dTp1OhMwTqmYEWscB5OXaPFuk5GJImx30faQJsjaZEUtx6D8WO4m4ltyYrzRwf3D7mG5eic1k=
  - secure: PO6KuNrjeKmclFMHdF4x5f9aLD962w0GM1Ynro09YAmG0gaWBdNIFjn4Lyq7AFQsA11C5AK1ZrA/bBOyuhmtVR1EFhfopTa448YbUnTN7t5W4cKOCGfA0+8+stW+ScH4r+WVwzBsNCrxMLN+DdSReBg+woHw/QbmSzYUuvacxqMxDIiQp3K55l9ctB1G0YCm5gvIwvFxF72ogDV1M7DjAu+tj8TDKIeDgSqybTo9LsbQV0yNguSbwI3+s9MIeYOPhR6ElXNOY3CRddLDPD4NUxClCtC7dnW5pH35MLdpmvSIiGp6eFUAYDwYoFy/4WDhjDir0gN5AxDA9WflaZfKgIoRkiEVplOEEcU7gfjqwoaRgZKdxxuBmuPxRfaEAkFBzcg/pfbTof4QbRkjnKJr2QEW7dZ0S/CPUpor/LWkRH4FxT+VfayrcpoqH9GnHMkVsBhAQkRgCMkqQ12tlYG9JidGB5RsOLK5NTyNu/5EfvmotWmmk1IIHCZphV90yLWvgZFfFvYZp5TTdWSXCFwfpuEybrv3AB0iaMKiu4scT384EQHfHAhlx3mPqhxdZSPKsa2jCZL6dxSrOyTJFSZFr3fJwROEI1mZlhMX+HvJfBLe9xlZJtbLUCzCutWXwZeu3c/nGVGpsqmlqCBHIY61rrEcZlcd5NHCobQTUzqCeb8=
  - secure: JQuuLT4Uwgx5RMURimJeA6WYwWz1jJ80hFVxyykSgmp3zpodbuaawNja2e6VvAxYqscTGvXEjwqIQyRV4EpHy7taHPVUKSsEUBv8zJTIlYGbbk4P1anDVbPsPNj67r2dPWVhR49b7pqu1cxDUC+BgWFHkMA70YrrYptg9hdxr0AirdWXALJNBNog3u0X15PC/Uv2GAWt39kRXNvS5fI9YhNjn8Voe1QvtMwRyUKbVclyitxxG/AVEYmKNfFRenrFP/Snl8rIe9RWbDYyVDq98TaC3VBfTRZEN+J+5voubuiNibLj4DR9ERmlTEm5XjrqCOcY1/1eGqivz/ZWiOyHwUeO9NQFEUk8Q3+7jGUXCz2dSzuBdexFWuXv9hCD6FG+fCJQS0u5C+Yx54pxNvNZQhTS76YV3KvMz33maKIsz6RrGO2N7K/oSOXoOWl6B1fAY6tPWcFBjNk5KUtVrsht3mMO7KZ/zu4c3wb8jqBoOKcraWHXUc01hBjYnY31MW2tw1YqR3QrzbMwMrLvlPlJS6pK3amG/ZyoE2HNb8dkxbeereB9jCI9BVx2NcYClXlvSUe8IRqx7Q/1VFJsyum+0xv5A1nISQci/Z7kpq1OTH24ZIeNn6Y05TSTd62/XPLE2BULWhkLS+nx1L5EUOa+ZBq5lcji/FTedb5NW9Z2/kM=
