language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- echo $TRAVIS_TAG
- echo $(git describe --abbrev=0 --tags)
- bash scripts/deploy.sh $TRAVIS_BRANCH
script:
- npm test
- npm run build
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_BUCKET_NAME"
  local-dir: build
  skip_cleanup: true
  on:
    repo: ahdeshmukh/react-shopping-cart
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id
  $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
env:
  global:
  - secure: L315zakph8F63UJnL9+bI/vSAuAEzzuXZh+SWNhVMBxB5+GAjwx8o9DZ2NgwGf90NP53NxNL2hhyr3t27skngqyrqrjatdjwFdTYVRuYVTNYu586qtlD7PRQHFHnwFBnUxl38/gK8y/up2iQzxmzelJpv8IqtUDBWydNugQSLzjE4q85zEg6/eb08a+7NO8u0qUXohgEuOe8ALBJ7n/pDVvypOJbupCuuzj012INhmGkoSrae+kwvsmYbdNAyJKYKSVU8/0RYzxL/OSFsY7a84ZO93PyCy5IDlQnvgDrxWe5YUO5ep9xmSlarrw1mRmamgEb1qSTDk8dWZqPFOs+loSlffU0PSBOMFF9N2PIDU6MmcPuP0aZZ0mkYnnCgyEijeCm6jrmosWBgbD979jqh/5OtlBz2rlg9fFfQA28FWt7odenz7SjVQtRsjtDzS09MCzXMnn0j9VgRKEyw+rSCxk5GTf0CEZpgGFILRIdJ57twOoekJnmWBPvMMeASL6bUe7o6UGvPXoNZOWCAoNFGhF1C5mmJ8NjSR8Nmto4X8kR+70tkqh3AmJ9ohq/+DbI0oDm1Iij8s1+9a+gNc4JCCYuzqNFbm2tp+KVE3K571JFyQh+ZJtEHYfKRfbm8QyWNU+aJdVjxqYOJPwZcWCKLcCa/k3qeaC5HZ06r+YUjOE=
  - secure: QqG2cXkjlAYTeG4+PpqN9xIB5U022R8eiLOTKsDYR3T/nraFmcSXuRbam5SG8ggC/REhebVMRCXvTtoWABqIDM6HZ3PQuppPRruwxMQ970yFgQ9sYqvJKe2GGMxpdcInKlpSKS/xEjXiqRU7hMMAdtTrixq9TmaaeyBN3DoMMhQsIhFumBqKY/u1gOy6vFDIGTpOtdw2pcv5I7qQoJjIfRe7t08sO7YA8CM3i5eIUlVfBrgzMdYdvMNlRM95sBAwpNyb+T7ujf9wjam+LHxjNr3CfTFU154wTwcZCCWamPtZMditrHS5iZ1p5hvmJtlV4eT5gjS5vH8j5jwlKkbrAA2vQilwHCcTM4eAnQ3ktjWcmn92Fv3fyVyxnm32c6ptnHzf3DCiaVN33oyDWI3EKPgRdlYaotUmrm6Yx8arqx95lXhWWZHav20C1MFHJ2vYnO55Yehdn/ERrToDcsOugeuWEr07KkhVpzP+nr5tTXWiEUOCegkxdNbiGvdp1JlPDfzIxRAKrEXgx6W14UMFuJDimoJq5Py3OfnH7JYmTz7AiRseqaQfQaMWR+l8WOk5SC3/OpaNbrTv9QBTgw2qEMa00I0TDt/08A9SMAJTUvxSPok4ty60jV9VvJP1h7q/i6ysDiSjQ4GRWzL0H2k8hcIKq8xbdi0cWgWzMC4nPJs=
