language: node_js
node_js:
  - "stable"
#install:
#  - pip install --user awscli
cache:
  directories:
    - node_modules
before_script:
  - echo $TRAVIS_TAG
  - echo $(git describe --abbrev=0 --tags) 
script:
  - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET_NAME
    local-dir: build
    skip_cleanup: true
    #acl: ''
    on:
      repo: ahdeshmukh/react-shopping-cart
      branch: master
      #condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"