language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- echo $TRAVIS_TAG
- echo $(git describe --abbrev=0 --tags)
- bash scripts/deploy.sh $TRAVIS_BRANCH
script:
- npm test
- npm run build
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_BUCKET_NAME"
  local-dir: build
  skip_cleanup: true
  on:
    repo: ahdeshmukh/react-shopping-cart
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id
  $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
env:
  global:
  - secure: F/du094X9KoOZ1zweMGdFmDVdvUofuL5ToDyQWmjjhLwHsoVBxgpFoBP9QEAU8ZBxU664XOQ0hnREnxo2L+jdilkpExOyCVmVSuZ2iaoAU7Oqz19YOdacLGvnmtSYzFmW/kbFrwXeaGOGUM8mqNB92qDjXvdL5TJx8r7LshG3sWaqZ2kngXANZhWGRjyf8mJumCfoZUVMto2RbszRlsS+HjiCKj3+B9POH0paL6TmNKWEj7PBSmWU6KuI/kCxlme/v63POzJV9w89aIQ2t825T+be314HbmiYbKnS5NDxWqBINok4Xr09VO6njBn6DgS089g2XQ+Yo2R4JwokvqfcaN8erJLqij9mE2OGEfmmXRyJ1K8vU3vqdgVcVUGXlPAlYD7Pwidyn9fiBX8IOcXE7C8Sre/80EmdYdS2PWGjryP3AiPN+UQ7FHSAPnUUsNOpwhbYcRESYvydAzbClvfYu46MbOsTPSL3nHvw8WLgQhy/eL6tYwhOTmbB++HERPbEuMZAB4YHKV4qN32x8+PFcnuRuJ2K+xR7HXCUtcXFUNRU053keb2g+VfeGteBZjM1D9Ff8xT7kC+JdjZl3SvYm7YgKp0gvQYIS5he/sQnpnYNCJKf+/5xKw9twAFQG9wVqb2EPTEpbwWlduBcopDdffAjwbIXQ3Z52Qjo6zklA8=
  - secure: mxu9+evL3xDdn8H2NqDYaKtID/4idFykwPw4wXe4SIwOgQW30s7OumRRAWLh2yS6rciffJLLAv2X1/x7OIbqZ46tiyoyLTlZI7KrhWLl66q6ZThFIgNehJA0258xa691MFagofCkEOtYN/a1GHJZf0QaAzL+fVn1tpbSU6iFthh1fOdcgcUwbH5JzxpKQ3ZvXji/0V9yqJYWTHLEx+XIe06EB5ll9WTFS4ENY+epa/Ndlf0pZTW+pLfh/FXxGG6PIJjVq3QAhI/6e2tQANnubvHqYOtkevTLXbPs6hnIFRZv37d94VQxSRIX7zvuNalITjjVxrHw3DLCorh6wT2VYRe09AVakt8lbfhb8ynhH8vJE2kK52Q7Bkv0qo3kJ7B4kOgbyo8WByXyEGcqBlfLhVsL+u5CnyZMMXaXFI/IaQEieiuykCtfnXbEd8286lCg3ZCnOzwnNAD6JnKx9ZajRpb84/5dfVN3RPHspiukvxFV1OucBDeLge32oyGBGcedPJnJbtfxjcKwJ8DNzci3Z8M+/fE+Q9LGO12uDHu5z2V0eE378Tjxgbsc8QQ6IQVuQwYbqI7bgwR++qbj08aajX3+RHD4T+2mhdHkhUf8k+WvSyj4kKpsyJNC2saTrxv6PVJbHiklQ0hNGZqEf3wgb0BuTIalyR6jg1+lrNGGE2Y=
